management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: 'Spring Bank'
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
logging:
  level:
    root: info
    name.seguri.java: debug