management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: 'Spring Bank'
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    database-change-log-table: 'SPRINGBANK__DATABASECHANGELOG'
    database-change-log-lock-table: 'SPRINGBANK__DATABASECHANGELOGLOCK'
logging:
  level:
    root: info
    name.seguri.java: debug