app:
  dir: @project.basedir@
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    security:
      protocol: SASL_SSL
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      group-id: spring-kafka-upstash
      properties:
        sasl:
          jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USER}" password="${KAFKA_PASS}";
          mechanism: SCRAM-SHA-256
        spring.json:
          trusted.packages: name.seguri.java.tutorials.springkafkaupstash
          value.default.type: name.seguri.java.tutorials.springkafkaupstash.Request
