management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  servlet:
    context-path: /
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
springdoc:
  # Custom property to switch between configuration style. Accepted values: [annotations, beans]
  config-style: 'annotations'
  api-docs:
    # Enables springdoc-openapi endpoint
    enabled: true
    # Where the spec is exposed. /v3/api-docs by default
    path: /api/svc-foo/v1.0/spec
  swagger-ui:
    # Enable swagger-ui
    enabled: true
    # Custom path of the swagger-ui HTML documentation, /swagger-ui.html by default
    path: /swagger-ui.html
    # Where the spec is supposed to be. /api/api to fix ingress
    url: /api/api/svc-foo/v1.0/spec
#    config-url: /swagger-config
swagger:
  server-base-path: /useless/path
